### ISSUE TITLE
[META] TODO

### ISSUE THREAD

**Issue by WindSekirun** [WindSekirun/Flights#1]
* 베이스
  * [ ] Vuex + Router
  * [ ] AppBar, Footer 등 구현
  * [ ] 데이터 구조체 모델화 (리스트, 상세)
* 메인 화면
   * [ ] 메인 화면 내 아이템 객체
 * 상세 화면
   * [ ] 스크린샷 나열
   * [ ] 구글 지도로 GPX 표시
   * [ ] 플라이트 플랜 Append
 * 정보 화면
   * [ ] 하드웨어 정보
   * [ ] 사용 모드 정보
